-- require("obsidian").setup({
--   dir = "~/Documents/Notes",
--   new_notes_location = "current_dir",
--   completion = {
--     nvim_cmp = true,
--     min_chars = 2,
--     -- Where to put new notes created from completion. Valid options are
--     --  * "current_dir" - put new notes in same directory as the current buffer.
--     --  * "notes_subdir" - put new notes in the default notes subdirectory.
--   },
--   finder = "telescope.nvim",
-- })

-- vim.keymap.set("n", "gf", function()
--   if require("obsidian").util.cursor_on_markdown_link() then
--     return "<cmd>ObsidianFollowLink<CR>"
--   else
--     return "gf"
--   end
-- end, { noremap = false, expr = true })
